---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Python
      dnf:
        name: python3
        state: present
    - name: Install pip
      dnf:
        name: python3-pip
        state: present
    - name: Install boto3 and botocore for Python
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        state: present
    - name: Remove existing git repository directory if it exists
      ansible.builtin.file:
        path: /home/ec2-user/shinsaegae-mini
        state: absent
      become: yes
    - name: Clone Git Repository
      git:
        repo: https://github.com/z9612/shinsaegae-mini3.git
        dest: /home/ec2-user/shinsaegae-mini
        update: yes
    # RDS 인스턴스 정보 조회
    - name: Get RDS instance information
      community.aws.rds_instance_info:
        region: ap-northeast-2
        db_instance_identifier: "terraform-mysql"
      register: rds_result
    - name: Import MySQL dump to RDS
      ansible.builtin.shell: |
        mysql -u nana -h {{ rds_result.instances[0].endpoint.address }} -D terraformdb -pnana1234 < /home/ec2-user/shinsaegae-mini/Dump20240118/project_user.sql
